site:
  title: Arconia

content:
  sources:
  - url: https://github.com/arconia-io/arconia.git
    branches: ~
    start_path: docs
    tags:
    - v*
    - '!v0.0.*'
    - '!v0.1.*'
    - '!v0.2.*'
    - '!v0.3.*'
    - '!v0.5.*'
    - '!v0.6.*'
    - '!v0.7.*'
    - '!v0.8.*'
    - '!v0.9.*'
    - '!v0.10.0'
    - '!v0.10.1'
    - '!v0.10.2'
    - '!v0.14.0'
  - url: https://github.com/arconia-io/arconia-cli.git
    branches: ~
    start_path: docs
    tags:
    - v*
    - '!v0.0.*'
    - '!v0.1.*'
    - '!v0.2.0'
    - '!v0.2.1'
    - '!v0.2.2'
    - '!v0.2.3'
    - '!v0.2.4'
    - '!v0.2.5'
    - '!v0.2.6'
    - '!v0.2.7'
    - '!v0.2.8'

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./supplemental-ui

urls:
  latest_version_segment: latest
  html_extension_style: indexify

output:
  clean: true
  dir: ./build/website/docs

asciidoc:
  extensions:
    - '@asciidoctor/tabs'
