site:
  title: Arconia
  start_page: arconia::index.adoc
content:
  sources:
  - url: https://github.com/arconia-io/arconia.git
    tags:
    - pattern: v*
    - pattern: early-access
      snapshot: true
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./supplemental-ui
urls:
  latest_version_segment: latest
  html_extension_style: indexify
output:
  clean: true
  dir: ./build/website/docs
