site:
  title: Arconia

content:
  sources:
  - url: https://github.com/arconia-io/arconia.git
    branches: ~
    start_path: docs
    tags:
    - v*
    - '!v0.0.*'
    - '!v0.1.*'
    - '!v0.2.*'
    - '!v0.3.*'
    - '!v0.5.0'
    - '!v0.5.1'
    - '!v0.5.2'
    - '!v0.5.3'
    - '!v0.5.4'

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./supplemental-ui

urls:
  latest_version_segment: latest
  html_extension_style: indexify

output:
  clean: true
  dir: ./build/website/docs
